name: util-npm-publish2

on:
  push:
    branches:
      - master
    paths:
      - src/**/*.ts
      - package.json
    paths-ignore:
      - src/**/*.spec.ts

jobs:
  build:
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'